---
- name: Base configuration for the new linux host
  hosts: "{{ target_host }}"
  vars_prompt:
  - name: target_host
    prompt: Please enter the target-host
    private: false

  pre_tasks:
  - name: Set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow

  roles:
  - upgrade-packages
  - zabbix-agentd-6.2
  - sshd-config
  - addusers

  tasks:
  - name: Clear old dependencies
    apt:
      autoremove: false

  - name: Check qemu-guest-agent
    apt:
      name: qemu-guest-agent
    notify: Start qemu agent
    when: ansible_facts['virtualization_type'] == 'kvm'

  handlers:
  - name: Start qemu agent
    systemd:
      name: qemu-guest-agent.service
      state: started
      enabled: true