---
- name: Show all available ansible_facts
  hosts: "{{ target_host }}"
  vars_prompt:
  - name: target_host
    prompt: Please enter the target-host
    private: no

  tasks:
  - debug:
      msg: "{{ ansible_facts }}"
