---
- name: Generate the new OpenSSH keypair
  openssh_keypair:
    path: /etc/ssh/ssh_host_rsa_key
    size: 4096
    type: rsa
  notify: Restart sshd.service

- name: Replace sshd_config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: '0644'
    owner: root
    group: root
  notify: Restart sshd.service
