---
# tasks file for roles/lxc-basic-config
- name: Update repositories cache and upgrade all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install zabbix-agent
  apt:
    name: zabbix-agent
  notify: Enable zabbix-agent.service

- name: Enable zabbix-agent.service
  systemd:
    name: zabbix-agent.service
    state: started
    enabled: yes

- name: Replace zabbix_agentd.conf file
  template:
    src: templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: '0644'
  notify: Restart zabbix-agent.service

- name: Replace sshd_config file
  template:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    mode: '0644'
  notify: Reload sshd.service

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

