---
- name: Add users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  loop:
  - username: mishagin
    password: '$1$jgc6rRQU$cC4oxStaOMj7kAMkxwC1N1'
    shell: /bin/bash
    comment: Nikita Mishagin
    groups:
    - sudo
  - username: sergey
    password: '$1$jgc6rRQU$cC4oxStaOMj7kAMkxwC1N1'
    shell: /bin/bash
    comment: Nikita Mishagin
    groups:
    - sudo

- name: Add public keys for users
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.publickey }}"
  loop:
  - username: mishagin
    publickey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC499ZksssxclICZQJS2tn+zWN+g8fe3U69R1RL26uMczTe5MK2JpvFhqXc9hld2uThHUXUI6VzHmUquwqZrUp1CYbTxf/4zqu8DJtabQt3Xot2UmdXdzi8MFYsiRf6ENlBMy6vpWkC0fHlkrku/nnElrcy1lD8gdShQFKGT6bDImfTi8v+uG7ElDlPDKgLYbe0Wa93L43NBfjKdRzYi/1mkhSusMfS3R2T3UKeThHlqFYpGmvH1gf77Uzk8oHHflCojqoyAK10CG0uf4deE2Jf27pNOiu3G9cvuIiSuqtZn1QGIYGhjSyfNcseBygCMuvDH/cOf3Ol2/NIZqmSSjIiyoLTRVh+qqPq1psHctg+VdaRkIuuC/s6/UVvfR5vjY96NYONffyP9rXKRzc6JbYEjBzwYZweZAVbyhXcXLMvvCtNth4WS1SJXEvC0G19iN6TKBmnY9ZjqbrP08S8ZHdZtQW9KCFZqhHHtTrVPvCLFzNgT3XOSMl64OKpkAi7KiUg8daFQ3JNey82N37ggnXtsvnCE7Z7NctLz/+05XTIwm/5iqCoF9uE47BJLtY3/yyB9epkTx8Dc7/QbfQqOO/6swW45IPRWQIdf/2eKksUWjPalTmxDyXDLATKU45VK/GOavw8cWBdSGTn7y6P3tNYGrQhesEiJ2CxzZpiHr8fkw== mishagin@asuslaptop'
  - username: sergey
    publickey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC499ZksssxclICZQJS2tn+zWN+g8fe3U69R1RL26uMczTe5MK2JpvFhqXc9hld2uThHUXUI6VzHmUquwqZrUp1CYbTxf/4zqu8DJtabQt3Xot2UmdXdzi8MFYsiRf6ENlBMy6vpWkC0fHlkrku/nnElrcy1lD8gdShQFKGT6bDImfTi8v+uG7ElDlPDKgLYbe0Wa93L43NBfjKdRzYi/1mkhSusMfS3R2T3UKeThHlqFYpGmvH1gf77Uzk8oHHflCojqoyAK10CG0uf4deE2Jf27pNOiu3G9cvuIiSuqtZn1QGIYGhjSyfNcseBygCMuvDH/cOf3Ol2/NIZqmSSjIiyoLTRVh+qqPq1psHctg+VdaRkIuuC/s6/UVvfR5vjY96NYONffyP9rXKRzc6JbYEjBzwYZweZAVbyhXcXLMvvCtNth4WS1SJXEvC0G19iN6TKBmnY9ZjqbrP08S8ZHdZtQW9KCFZqhHHtTrVPvCLFzNgT3XOSMl64OKpkAi7KiUg8daFQ3JNey82N37ggnXtsvnCE7Z7NctLz/+05XTIwm/5iqCoF9uE47BJLtY3/yyB9epkTx8Dc7/QbfQqOO/6swW45IPRWQIdf/2eKksUWjPalTmxDyXDLATKU45VK/GOavw8cWBdSGTn7y6P3tNYGrQhesEiJ2CxzZpiHr8fkw== mishagin@asuslaptop'
