---
# tasks file for /ansible/roles/proxmox-config
- name: Replace repository file
  template:
    src: templates/sources.list
    dest: /etc/apt/sources.list
    mode: '0644'

- name: Replace .bashrc file
  template:
    src: templates/bashrc
    dest: /root/.bashrc
    mode: '0644'

- name: Remove pve-enterprise file
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
