---
- name: Install zabbix repository
  apt:
    deb: https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-{{ zabbix_release }}%2Bdebian{{ ansible_facts['distribution_version'] }}_all.deb

- name: Install zabbix agent
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes

