---
- name: Create a zabbix directory if it does not exist
  file:
    path: /etc/zabbix
    state: directory
    mode: '0755'

- name: Replace zabbix_agentd.conf file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: '0644'
  notify: Restart zabbix-agent.service

- name: Import instructions for Ubuntu
  import_tasks: ubuntu_tasks.yml
  when: ansible_facts['distribution'] == 'Ubuntu' and (ansible_facts['distribution_version'] == '18.04' or ansible_facts['distribution_version'] == '20.04' or ansible_facts['distribution_version'] == '22.04')

- name: Import instructions for Debian
  import_tasks: debian_tasks.yml
  when: ansible_facts['distribution'] == 'Debian' and (ansible_facts['distribution_version'] == '10' or ansible_facts['distribution_version'] == '11')

- name: Enable zabbix-agent.service
  systemd:
    name: zabbix-agent.service
    state: started
    enabled: yes
