---
- name: Basic configuration for the new LXC
  hosts: 
# Here need to enter a host-group

  tasks:
  - name: Update repositories cache and upgrade all packages
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install zabbix-agent package
    apt:
      name: zabbix-agent

  - name: Generate an OpenSSH keypair
    community.crypto.openssh_keypair:
      path: /etc/ssh/ssh_host_rsa_key
    register: sshkeygen

  - name: Configuration rsa-key in sshd_server
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#HostKey /etc/ssh/ssh_host_rsa_key'
      line: 'HostKey /etc/ssh/ssh_host_rsa_key'
    register: sshdkey

  - name: Disable password authentication in sshd_server
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PasswordAuthentication yes'
      line: 'PasswordAuthentication no'
    register: sshdpasswd

  - name: Reload sshd.service
    ansible.builtin.systemd:
      name: sshd.service
      state: reloaded
    when: sshkeygen.changed or sshdkey.changed or sshdpasswd.changed

  - name: Set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow
